### ISSUE TITLE
Unable to send mail

### ISSUE THREAD

**Issue by ukch** [fastmonkeys/sentry-on-heroku#12]
I set up my app using the 'Deploy to Heroku' button. It seems to work fine, but I noticed it wasn't sending mail, so I went to https://MYAPPNAME.herokuapp.com/manage/status/mail/, clicked the 'Send a test email to ...' button, and recived the following error:

    'module' object has no attribute 'sslwrap'

Unfortunately the error does not appear to be logged to the Heroku log, so I can't say any more than that at the moment.

**Comment by ingojoseph** [comment]
I get the same error. @ukch, did you already found a solution?

**Comment by tucksaun** [comment]
I encountered the same error months ago and managed to fixed it by pinning to python 2.7.8.

On Heroku you can do that by adding a `runtime.txt` file with ```python-2.7.8``` as content at the root of your project. Commit, push and it should work.

**Comment by ingojoseph** [comment]
@tucksaun Thanks a lot! This works for me as well.

**Comment by tucksaun** [comment]
great :)
