### ISSUE TITLE
No event showing

### ISSUE THREAD

**Issue by natsu90** [fastmonkeys/sentry-on-heroku#15]
Hi, I installed using the Heroku button. Logged in, copied and pasted the DSN URL to my other app, tried to throw 404 error but no event showing. What did I miss? Please help.

**Comment by jpvanhal** [comment]
404s are logged by Raven by default. I don't know what language/framework you're using, but in Django, for example, you could do [something like this](https://raven.readthedocs.org/en/latest/integrations/django.html#logging) to log 404s
