### ISSUE TITLE
Mandrill are withdrawing their plans on Heroku

### ISSUE THREAD

**Issue by ukch** [fastmonkeys/sentry-on-heroku#21]
I received this email yesterday:

> The Mandrill team has chosen not to continue development of this add-on. It is not possible to migrate your existing account directly to Mandrill; a new account will need to be created.
>
> The Mandrill add-on will be removed from all apps in 60 days. We advise you to remove it yourself before that either via the Dashboard or via the CLI.
>  
> 
> Please consider using SendGrid or another add-on in Elements for your app's email needs. Contact our support team if you run into any problems.

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

They are giving 100,000 free emails/month.

**Comment by richleland** [comment]
@ukch note that if you're interested in SparkPost's Heroku add-on we're waiting for them to update pricing - it's going to be dramatically different (in an awesome kinda way) :smile:
